# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    Imk\FormBundle\Factory\LoadConfigFactory:
        arguments: ['@filesystem','@kernel','@parameter_bag']
        public: false
        autowire: false
    Imk\FormBundle\Factory\Form\Form:
        arguments: ['@Imk\FormBundle\Factory\LoadConfigFactory']
        public: false
        autowire: false
    Imk\FormBundle\Factory\Form\FormFields:
        arguments: ['@Imk\FormBundle\Factory\Form\Form']
        public: false
        autowire: false
    Imk\FormBundle\Factory\Builder\DtoBuilder:
        arguments: ['@maker.generator','@maker.renderer.form_type_renderer', '@kernel']
    Imk\FormBundle\Factory\Builder\FormBuilder:
        arguments: ['@maker.generator','@maker.renderer.form_type_renderer', '@kernel']
    Imk\FormBundle\Utils\ImkCmdManager:
        arguments:
            - '@Imk\FormBundle\Factory\Form\Form'
            - '@Imk\FormBundle\Factory\Form\FormFields'
            - '@Imk\FormBundle\Factory\Builder\DtoBuilder'
            - '@Imk\FormBundle\Factory\Builder\FormBuilder'
    Imk\FormBundle: ~
    Imk\FormBundle\Command\GenerateAllCommand: ~
    Imk\FormBundle\Command\GenerateFormCommand:
        arguments: ['@Imk\FormBundle\Utils\ImkCmdManager']
    Imk\FormBundle\Command\GenerateDtoCommand:
        arguments: ['@Imk\FormBundle\Utils\ImkCmdManager']
    Imk\AuthBundle\Factory\FileLoadConfig:
        arguments: ['@kernel']
    Imk\AuthBundle\Command\ImkAuthCreateUser: ~

